[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
framework = arduino
upload_protocol = stlink
monitor_speed = 115200
monitor_eol = CRLF
build_flags =
    -DENABLE_HWSERIAL1
    -DENABLE_HWSERIAL2
    -DENABLE_HWSERIAL3
    -DENABLE_HWSERIAL6
